services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: yuri
      POSTGRES_PASSWORD: password
      POSTGRES_DB: investment_learner_development
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
